version: '3'

services:
  server:
    build: ./
    image: nodejs-server:prod
    environment:
      - "NODE_ENV=production"
      - "SERVER_PORT=7000"
      - "SWAGGER_ENABLE=1"
    ports:
      - "7000:7000"
    restart: always